# MySQL headless service
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-svc
  namespace: cep-project1
  labels:
    app: wordpress
spec:
  # This creates a headless service
  clusterIP: None
  ports:
    - port: 3306
      targetPort: 3306
  selector:
    app: wordpress

# MySQL Persistent Volume mapped to an NFS volume
---
kind: PersistentVolume
apiVersion: v1
metadata:
   name: mysql-pv
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  nfs:
    path: /mnt/nfs-shared/db
    server: 10.1.0.12
    readOnly: false

# MySQL PersistentVolumeClaim
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mysql-claim
  namespace: cep-project1
spec:
  storageClassName: manual
  volumeName: mysql-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

# MySQL App Deployment
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: cep-project1
  labels:
    app: wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
        - image: mysql:8
          name: mysql
          env:
            - name: MYSQL_DATABASE
              value: wpdb
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                   name: mysql-pass
                   key: password
          ports:
            - containerPort: 3306
              name: mysql
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: mysql-claim
