# WordPress App Service
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: wordpress-101
  name: wordpress-101
  namespace: wordpress
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      nodePort: 30396
  selector:
    app: wordpress-101

# PersistentVolume for WordPress
---
kind: PersistentVolume
apiVersion: v1
metadata:
   name: wp-app-pv-101
   namespace: wordpress
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  nfs:
    path: /mnt/hd1/wordpress/incubacoop.ufrpe.br/web
    server: 172.16.69.59
    readOnly: false

# WordPress App PersistentVolumeClaim
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: wp-app-claim-101
  namespace: wordpress
spec:
  storageClassName: manual
  volumeName: wp-app-pv-101
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

# WordPress App Deployment
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-101
  namespace: wordpress
  labels:
    app: wordpress-101
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress-101
  template:
    metadata:
      labels:
        app: wordpress-101
    spec:
      containers:
        - image: wordpress
          name: wordpress-101
          env:
          - name: WORDPRESS_DB_HOST
            value: mysql-svc-101
          - name: WORDPRESS_DB_USER
            value: wordpress
          - name: WORDPRESS_DB_NAME
            value: wpdb
          - name: WORDPRESS_DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-pass-101
                key: password
          - name: WORDPRESS_DEBUG
            value: "1"
          ports:
            - containerPort: 80
              name: wordpress-101
          volumeMounts:
            - name: wordpress-persistent-storage-101
              mountPath: /var/www/html
      volumes:
        - name: wordpress-persistent-storage-101
          persistentVolumeClaim:
            claimName: wp-app-claim-101
